---
HOSTS:
  debian9:
    platform: debian-9-amd64
    packaging_platform: debian-9-amd64
    hypervisor: vagrant
    roles:
    - agent
    - default
CONFIG:
  nfs_server: none
  consoleport: 443
  box: debian/stretch64
  masterless: true
  puppet_collection: puppet5
  type: agent
